name: flock_it
author: wfalcon0x
version: 0.1.0
description: A network of self-repaying loan agents - the agents autonomously pay
  back a user's loan using strategies based on the user's risk tolerance
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeigkh3bwwjzgbl3jlcbovrf67ikisndygihsutgqlijhgie3z44ao4
fingerprint_ignore_patterns: []
agent: wfalcon0x/flock_it:0.1.0:bafybeidtqhstenmsknzwgq4fpf4aabkfi5vhaqxma5nrbmqbv64rgpeyx4
number_of_agents: 1
deployment: {}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    gnosis:
      address: ${GNOSIS_LEDGER_RPC:str:http://localhost:8545}
      chain_id: ${GNOSIS_CHAIN_ID:int:100}
      poa_chain: ${IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${DEFAULT_GAS_PRICE_STRATEGY:str:eip1559}
---
public_id: valory/configs:0.19.0
type: connection
config:
  MY_API_KEY: ${MY_API_KEY:str:yyyyyyyy}
  SAFE_CONTRACT_ADDRESSES: ${SAFE_CONTRACT_ADDRESSES:str:0x0000000000000000000000000000000000000000}
